### ISSUE TITLE
Runtime error when using grayscale color configuration

### ISSUE THREAD

**Issue by tjljw2000** [neosr-project/neosr#93]
```
Traceback (most recent call last):
  File "C:\Project\ai\neosr\train.py", line 374, in <module>
    train_pipeline(str(root_path))
  File "C:\Project\ai\neosr\train.py", line 280, in train_pipeline
    model.optimize_parameters(current_iter)  # type: ignore[reportFunctionMemberAccess,attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\ai\neosr\neosr\models\image.py", line 702, in optimize_parameters
    self.closure(current_iter)
  File "C:\Project\ai\neosr\neosr\models\image.py", line 545, in closure
    l_g_consistency = self.cri_consistency(self.output, self.gt)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\neosr\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\neosr\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\ai\neosr\neosr\losses\consistency_loss.py", line 163, in forward
    input_luma = self.rgb_to_l_star(net_output_blur)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\ai\neosr\neosr\losses\consistency_loss.py", line 132, in rgb_to_l_star
    img = img @ torch.tensor([0.2126, 0.7152, 0.0722])
          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\neosr\Lib\site-packages\torch\utils\_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: size mismatch, got input (294912), mat (294912x1), vec (3)
```

Here is my configuration:

```toml
name = "4x_unimanga"
model_type = "image"
scale = 4
use_amp = true
bfloat16 = true
fast_matmul = true
#compile = true
#manual_seed = 1024

[datasets.train]
type = "paired"
dataroot_gt = 'C:\Project\ai\manga-dataset\sel2-l\hq'
dataroot_lq = 'C:\Project\ai\manga-dataset\sel2-l\lq'
patch_size = 48
batch_size = 8
color = "y"
#accumulate = 1
#augmentation = [ "none", "mixup", "cutmix", "resizemix" ] # [ "cutblur" ]
#aug_prob = [ 0.5, 0.1, 0.1, 0.1 ] # [ 0.7 ]

[datasets.val]
name = "val"
type = "paired"
color = "y"
dataroot_gt = 'C:\Project\ai\manga-dataset\val2-l\hq'
dataroot_lq = 'C:\Project\ai\manga-dataset\val2-l\lq'
[val]
val_freq = 1000
tile = 200
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
[val.metrics.dists]
type = "calculate_dists"
better = "lower"

[path]
#pretrain_network_g = 'C:\Project\ai\pretrained-models\RealESRGAN_x4plus_anime_6B.pth'
#pretrain_network_d = 'experiments\pretrain_d.pth'

[network_g]
type = "esrgan"
num_in_ch = 1
num_out_ch = 1
num_feat = 64
num_block = 23
num_grow_ch = 32

[network_d]
type = "dunet"
in_ch = 1
dim = 64

[train]
ema = 0.999
grad_clip = false

[train.optim_g]
type = "adan_sf"
lr = 1e-3
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 1600

[train.optim_d]
type = "adan_sf"
lr = 1e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 600

#  losses
[train.mssim_opt]
type = "mssim_loss"
loss_weight = 1.0

[train.consistency_opt]
type = "consistency_loss"
loss_weight = 1.0

[train.perceptual_opt]
type = "vgg_perceptual_loss"
loss_weight = 0.5
criterion = "huber"

[train.gan_opt]
type = "gan_loss"
gan_type = "bce"
loss_weight = 0.1

[logger]
total_iter = 600000
save_checkpoint_freq = 1000
use_tb_logger = true
save_tb_img = true
print_freq = 100
```

**Comment by umzi2** [comment]
consistency_loss - essentially a loss of color, and you have 1 channel
