### ISSUE TITLE
train realersgan -> torch error

### ISSUE THREAD

**Issue by abcnorio** [neosr-project/neosr#94]
Hello,

while training a real-ersgan model

```
08-12-2024 12:00 AM | INFO: [ epoch:   0 ] [ iter: 32,600 ] [ performance: 4.022 it/s ] [ lr: 8.00e-04 ] [ eta: 2 days, 18:51:02 ] [ l_g_mssim: 4.7528e-01 ] [ l_g_consistency: 4.9110e-01 ] [ l_g_percep: 3.5055e-01 ] [ l_g_gan: 1.7565e+00 ] [ l_g_total: 3.0734e+00 ] [ l_d_real: 4.9024e-08 ] [ out_d_real: 1.7784e+01 ] [ l_d_fake: 1.5977e-10 ] [ out_d_fake: -1.7565e+01 ] [ l_d_total: 2.4592e-08 ]
08-12-2024 12:00 AM | INFO: [ epoch:   0 ] [ iter: 32,700 ] [ performance: 4.065 it/s ] [ lr: 8.00e-04 ] [ eta: 2 days, 18:50:27 ] [ l_g_mssim: 5.6157e-01 ] [ l_g_consistency: 5.9041e-01 ] [ l_g_percep: 3.6276e-01 ] [ l_g_gan: 1.7891e+00 ] [ l_g_total: 3.3039e+00 ] [ l_d_real: 3.6554e-08 ] [ out_d_real: 1.8129e+01 ] [ l_d_fake: 4.5475e-11 ] [ out_d_fake: -1.7891e+01 ] [ l_d_total: 1.8300e-08 ]
08-12-2024 12:01 AM | INFO: [ epoch:   0 ] [ iter: 32,800 ] [ performance: 4.061 it/s ] [ lr: 8.00e-04 ] [ eta: 2 days, 18:49:56 ] [ l_g_mssim: 5.6816e-01 ] [ l_g_consistency: 6.6751e-01 ] [ l_g_percep: 3.6129e-01 ] [ l_g_gan: 1.8294e+00 ] [ l_g_total: 3.4264e+00 ] [ l_d_real: 2.9898e-08 ] [ out_d_real: 1.8301e+01 ] [ l_d_fake: 5.4570e-12 ] [ out_d_fake: -1.8294e+01 ] [ l_d_total: 1.4952e-08 ]
Traceback (most recent call last):
  File "/home/XXX/neosr/neosr/train.py", line 374, in <module>
    train_pipeline(str(root_path))
  File "/home/XXX/neosr/neosr/train.py", line 280, in train_pipeline
    model.optimize_parameters(current_iter)  # type: ignore[reportFunctionMemberAccess,attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/neosr/neosr/neosr/models/image.py", line 702, in optimize_parameters
    self.closure(current_iter)
  File "/home/XXX/neosr/neosr/neosr/models/image.py", line 607, in closure
    torch.nn.utils.clip_grad_norm_(
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/nn/utils/clip_grad.py", line 30, in _no_grad_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/nn/utils/clip_grad.py", line 99, in clip_grad_norm_
    raise RuntimeError(
RuntimeError: The total norm of order 2.0 for gradients from `parameters` is non-finite, so it cannot be clipped. To disable this error and scale the gradients by the non-finite norm anyway, set `error_if_nonfinite=False`
```

This came after some time. Call:

`python train.py -opt options/train_esrgan_otf_v1.toml`

and the `.toml` file is standard, only image path was adjusted.

```
[datasets.train]
type = "otf"
dataroot_gt = '/home/XXX/neosr/neosr/GENAI_conv-to-jpg_hardlinks-multiscale-sub_selected'
patch_size = 64
batch_size = 8
#accumulate = 1
```

No eval, ie. commented out

```
#[datasets.val]
etc...
```

network standard:

```
[network_g]
type = "esrgan"

[network_d]
type = "ea2fpn"
```

OS: Debian sid, nvidia rtx4090

Nothing else was changed.
How can this be solved?

Thanks!

**Comment by neosr-project** [comment]
Hi. Please update neosr, this has been fixed a few days ago. I'd also recommend using the new configuration files provided in `options/`, they have been changed as well.
