### ISSUE TITLE
AttriubuteError: 'NoneType' object has no attribute 'astype' | after several iterations

### ISSUE THREAD

**Issue by abcnorio** [neosr-project/neosr#95]
Hello,

following the issue yesterday and after doing `git pull` and using the new `.toml` config the following error came up:

```
[...]
-04 ] [ l_g_gan: 2.3772e+00 ] [ l_g_total: 2.7255e+00 ] [ l_d_real: 2.4421e-08 ] [ out_d_real: 1.7500e+01 ] [ l_d_fake: 0.0000e+00 ] [ out_d_fake: -2.2125e+01 ] [ l_d_total: 1.2211e-08 ]
09-12-2024 07:39 AM | INFO: [ epoch:   0 ] [ iter: 89,800 ] [ performance: 3.754 it/s ] [ lr: 8.00e-04 ] [ eta: 2 days, 19:16:12 ] [ l_g_mssim: 1.0925e-01 ] [ l_g_fdl: 2.1257e-01 ] [ l_g_consistency: 1.8345e-02 ] [ l_g_ldl: 1.5801e-04 ] [ l_g_gan: 1.6490e-02 ] [ l_g_total: 3.5681e-01 ] [ l_d_real: 2.3266e-08 ] [ out_d_real: 1.7625e+01 ] [ l_d_fake: 0.0000e+00 ] [ out_d_fake: -2.2250e+01 ] [ l_d_total: 1.1633e-08 ]
09-12-2024 07:40 AM | INFO: [ epoch:   0 ] [ iter: 89,900 ] [ performance: 3.725 it/s ] [ lr: 8.00e-04 ] [ eta: 2 days, 19:15:48 ] [ l_g_mssim: 1.0984e-01 ] [ l_g_fdl: 1.3573e-01 ] [ l_g_consistency: 1.8399e-02 ] [ l_g_ldl: 1.0377e-04 ] [ l_g_gan: 2.6698e+00 ] [ l_g_total: 2.9339e+00 ] [ l_d_real: 2.3358e-08 ] [ out_d_real: 1.7625e+01 ] [ l_d_fake: 0.0000e+00 ] [ out_d_fake: -2.2375e+01 ] [ l_d_total: 1.1679e-08 ]
Traceback (most recent call last):
  File "/home/XXX/neosr/neosr/train.py", line 406, in <module>
    train_pipeline(str(root_path))
  File "/home/XXX/neosr/neosr/train.py", line 372, in train_pipeline
    train_data = prefetcher.next()  # type: ignore[reportPossiblyUnboundVariable]
                 ^^^^^^^^^^^^^^^^^
  File "/home/XXX/neosr/neosr/neosr/data/prefetch_dataloader.py", line 108, in next
    self.preload()
  File "/home/XXX/neosr/neosr/neosr/data/prefetch_dataloader.py", line 93, in preload
    self.batch = next(self.loader)  # self.batch is a dict
                 ^^^^^^^^^^^^^^^^^
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise(
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/miniconda3/envs/neosr/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/XXX/neosr/neosr/neosr/data/otf_dataset.py", line 145, in __getitem__
    img_gt = imfrombytes(img_bytes, float32=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/neosr/neosr/neosr/utils/img_util.py", line 179, in imfrombytes
    img = img.astype(np.float32) / 255.0
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'astype'
```

context is still real-esrgan, debian sid, install of `neosr` as outlined here, for the `.toml` config only paths were adjusted ie. standard.

Thanks!

**Comment by abcnorio** [comment]
Thanks for pointing that out! Looks like this was really the problem, it did not break again. Will work with `lmdb` or `meta_info` file from now on just to be sure. With thousands of files within a folder it can happen that a non-related file was added and "forgotten" (here it was just some tab file with scores from previous quality scoring).
